# Generated by Django 4.0.4 on 2022-07-17 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=100, null='True')),
                ('date', models.DateTimeField(null='True')),
                ('task_type', models.CharField(max_length=100, null='True')),
            ],
        ),
    ]
