# Generated by Django 4.0.4 on 2022-07-17 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_alter_person_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='sr_no',
            field=models.CharField(max_length=100, null='True'),
            preserve_default='True',
        ),
    ]
